import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../../app/globals.css'
import TopNav from '@/components/navbars/TopNav'
import Footer from '@/components/navbars/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, offerTop
}: {
  children: React.ReactNode, offerTop: boolean
}) {
  return (
    <html lang="en">
      
      <body >
        <TopNav offerTop={offerTop}/>
        {/* {children} */}
        <Footer/>
        </body>
    </html>
  )
}
